export enum ButtonVariants {
  PRIMARY = 'primary',
  SECONDARY = 'secondary',
  SUCCESS = 'success',
  DANGER = 'danger',
  WARNING = 'warning',
  INFO = 'info',
  LIGHT = 'light',
  DARK = 'dark',
  TRADEMARK = 'trademark',
  CTA = 'cta',
  BLACK = 'black',
  WHITE = 'white',
  GRAY = 'gray',
  OUTLINE_PRIMARY = 'outline-primary',
  OUTLINE_SECONDARY = 'outline-secondary',
  OUTLINE_SUCCESS = 'outline-success',
  OUTLINE_DANGER = 'outline-danger',
  OUTLINE_WARNING = 'outline-warning',
  OUTLINE_INFO = 'outline-info',
  OUTLINE_CTA = 'outline-cta',
  OUTLINE_BLACK = 'outline-black',
  OUTLINE_WHITE = 'outline-white',
  OUTLINE_GRAY = 'outline-gray',
}
